name: h_foundation
description: flutter foundation  sdk of chenhao
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  logger:
  logger_flutter_viewer: ^0.8.0
  get:
  shared_preferences: ^2.2.1
  overlayment: ^0.2.1
  hotkey_manager:
    path: ../hotkey_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
